### ISSUE TITLE
Limits are not pushed down

### ISSUE THREAD

**Issue by erizocosmico** [src-d/gitbase-spark-connector#33]
If limits are not pushed down a query with UDFs will require every single record to pass through the UDFs instead of just a certain limit.

**Comment by ajnavarro** [comment]
I did some tests and even if the limit is not pushed down, we are only fetching the number of elements that Spark needs, so maybe is not a huge problem on limits in the topmost query.

**Comment by erizocosmico** [comment]
You mean if spark uses 10 elements, we only get 10 elements from gitbase? Last time I checked it was super slow. Don't remember well if all elements were retrieved from gitbase

**Comment by ajnavarro** [comment]
Yes, exactly that. I can check it again tomorrow to be sure.
