### ISSUE TITLE
Dates are casted to STRING

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase-spark-connector#35]

**Comment by ajnavarro** [comment]
Maybe this is a default behavior on Spark, and we are pushing down everything, even the casts to gitbase.

**Comment by kuba--** [comment]
@ajnavarro - any details, because when I query `commits` (where we have 2 timestamps) at the end in spark I also get timestamps:
```
val df = spark.sql("SELECT * FROM commits LIMIT 1")

      for (row <- df.collect()) {
          System.out.printf("commit_author_when: %s committer_when: %s\n",
            row.getAs("commit_author_when").getClass(), row.getAs("committer_when").getClass())
      }
```

prints:
```
commit_author_when: class java.sql.Timestamp committer_when: class java.sql.Timestamp
```

**Comment by kuba--** [comment]
Cannot reproduce it.

---

I'm sending from connector: `SELECT commit_author_when, committer_when FROM commits`

gitbase receives:
 ```
action=query address="127.0.0.1:50285" connection_id=38 duration="318.794µs" pid=145 query="SELECT @@max_allowed_packet,@@system_time_zone,@@time_zone,@@auto_increment_increment" success=true system=audit user=root
DEBU[0538] executing query                               query="SELECT commits.`commit_author_when`, commits.`committer_when` FROM commits"
```

and connector prints:
`commit_author_when: 2017-12-29 09:13:27.0 (class java.sql.Timestamp) committer_when: 2017-12-29 09:13:27.0 (class java.sql.Timestamp)`

so everything looks fine
