### ISSUE TITLE
Add notebook with examples.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase-spark-connector#40]
Add a notebook with some examples. Add this notebook to the generated docker container.

**Comment by erizocosmico** [comment]
Now that https://github.com/src-d/gitbase/issues/639 is fixed, I will add some examples with UAST functions.

**Comment by erizocosmico** [comment]
Update: can't add uast examples. Even if https://github.com/src-d/gitbase/issues/639 is solved, it's still affected by https://github.com/src-d/gitbase-spark-connector/issues/32

**Comment by ajnavarro** [comment]
Fix here: https://github.com/src-d/gitbase-spark-connector/pull/48
