### ISSUE TITLE
Releases must be uploaded to sonatype.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase-spark-connector#43]
Make releases to be uploaded to sonatype.

We need to do two kind of releases:
- Fat-jar: jar with all the needed dependencies to make it work with spark submit commands.
- Standard jar: to make possible to add this connector as a dependency on other projects. 

We can get more info of how to do this from https://github.com/src-d/jgit-spark-connector

**Comment by erizocosmico** [comment]
Issue on Sonatype: https://issues.sonatype.org/browse/OSSRH-44509
