### ISSUE TITLE
Add docs on how to run the docker image

### ISSUE THREAD

**Issue by erizocosmico** [src-d/gitbase-spark-connector#45]
To run the docker image the following things are required:
- Gitbase instance running and accessible from the container
- Bblfshd instance running and accessible from the container
- Gitbase must be able to access Bblfshd
- Register the gitbase source with the correct endpoint

For this, we should explain that all three containers need to be on the same network, and that gitbase should be started with `-e BBLFSH_ENDPOINT=bblfshd_container_name:9432`

Otherwise might cause frustration on users, because tying all these things together is neither simple nor obvious for a newcomer (even I struggled with this and I know the components).

**Comment by ajnavarro** [comment]
Maybe use docker compose?

**Comment by erizocosmico** [comment]
Docker compose is not pushable to docker hub. In docker hub we can only have the image itself. We can, of course, supply a docker compose, but remember that repos needs to be configured. Not sure if docker compose allows you to pass things from the CLI to change volumes, for example. If not, you would need to modify the yaml of the docker compose every time you need to change the repos, which is far from ideal.
And even if we provide a docker compose yaml, we should explain all these things

**Comment by kuba--** [comment]
how about `docker stack deploy`?
https://docs.docker.com/engine/swarm/stack-deploy/
