### ISSUE TITLE
Pushdown rules

### ISSUE THREAD

**Issue by erizocosmico** [src-d/gitbase-spark-connector#6]
Rules for community version:
- [x] join pushdown
- [x] #20 aggregations pushdown
- [x] #19 functions pushdown (UAST functions LANGUAGE function)

**Comment by ajnavarro** [comment]
@erizocosmico note that joins and aggregations rules using one gitbase node are basically a passthrough, checking joins conditions to see if the join will be squashed on gitbase side.

If a join is not squasheable, is not worth it to pushdown it.
