### ISSUE TITLE
Provide specs for external data sources

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase-spark-connector#75]
Add some documentation or links to supported Spark data sources, like JSON, parquet or JDBC (check if there are more of them).

We can add some usage examples, like:

- How to save to parquet file some output from a gitbase query.
- How to use GSC udfs on top of that extracted parquet file.
- How to join gitbase output with some external data in JSON.

**Comment by kuba--** [comment]
Regarding retrospective meeting - would be great to have more details here ;-)

**Comment by ajnavarro** [comment]
@kuba-- updated.
