### ISSUE TITLE
REGEXP inconsistencies depending where the expression is executed

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase-spark-connector#77]
JVM and Go regular expression engine have different syntax. This might cause on some queries differences depending where the expression is executed.

We need to find a solution to avoid this problem.

**Comment by kuba--** [comment]
Isn't solved after we upgrade mysql server and make the oniguruma a default regexp engine for gitbase?

**Comment by ajnavarro** [comment]
oniguruma regex syntax will be different from JVM one. Maybe a possible solution is document the problem and also the common syntax between oniguruma and JVM.

**Comment by kuba--** [comment]
...or maybe we can use https://github.com/jruby/joni in spark - wdyt?

**Comment by ajnavarro** [comment]
Change the actual REGEXP on spark will be really difficult. They are doing things like translate execution tree to code and more complicated stuff.

**Comment by erizocosmico** [comment]
All the regexp expressions in Spark are here: https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/regexpExpressions.scala

Maybe we could experiment with just copying these and substituting the default engine with joni and using a rule to translate Spark expressions with ours. I mean, it could get messy, but may be worth the shot.
