### ISSUE TITLE
Make work UDFs with variable input arguments

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase-spark-connector#83]
Right now udfs that have variable input arguments are not working correctly if you don't use all of them.

We need to find a way to register custom udfs that allows variable arguments.

**Comment by erizocosmico** [comment]
I've been doing some research on overloading Spark UDFs and the only way I've found to do this is using Hadoop Hive, which apparently supports overloading.

Using spark alone, I haven't found a way to do this.
I've tried using `Option[T]` with default value, `Any*`, registering several with the same name, etc, etc and none of these options work.

All Spark functions that take a variable number of arguments, such as concat or substring, are implemented as expressions in spark, not as user defined functions. So perhaps there is just no way to do this.

Another option could be to just use `function_name`, `function_name2` and `function_name3` and translate those to just `function_name` when building the query for gitbase. I don't know how feasible implementing our own expressions will be.

WDYT? @ajnavarro @kuba--

**Comment by kuba--** [comment]
I know `function_name`, `function_name2` and `function_nameX` doesn't looks good, but it can be the simplest way. Moreover if take a look into a scala structures we have `Tuple`, but also `Tuple2`, ...`TupleN`. So, maybe it can be even more scala idiomatic.

**Comment by ajnavarro** [comment]
Maybe we should do the same as is doing Spark, implement our udfs as expressions instead of using the udf exposed API.

**Comment by erizocosmico** [comment]
Yup, I found how to make and register custom expressions so I'm doing that instead.

**Comment by dpordomingo** [comment]
just pinging myself to review again https://github.com/src-d/gitbase-spark-connector/issues/81 once this is merged :dancer:
